# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43a4cbd78ec5fa3d2e9641bac5c9f166f5ecc9ee76aa93971d4acf401b656de073e552a8bf0e3cec883caaa55b0f3e9adf5f8429405ce247333ca527a9d36fbf

test:
  secret_key_base: fbed6252f612c5e9f380ecc15b6dfd985ae9d4f6a538171c04c23e0e37f72cd7d4a523d49cedeeddb18b7133ad7337f4d70fb3e18a9749b24f0dd57745bc397c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
